package com.gaop.huthelperdao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COURSE_GRADE".
 */
public class CourseGrade {

    private Long id;
    private String XN;
    private String XQ;
    private String XKKH;
    private String KCMC;
    private String XF;
    private String CJ;
    private String ZSCJ;
    private String BKCJ;
    private String JD;
    private String CXBJ;
    private String KCXZ;

    public CourseGrade() {
    }

    public CourseGrade(Long id) {
        this.id = id;
    }

    public CourseGrade(Long id, String XN, String XQ, String XKKH, String KCMC, String XF, String CJ, String ZSCJ, String BKCJ, String JD, String CXBJ, String KCXZ) {
        this.id = id;
        this.XN = XN;
        this.XQ = XQ;
        this.XKKH = XKKH;
        this.KCMC = KCMC;
        this.XF = XF;
        this.CJ = CJ;
        this.ZSCJ = ZSCJ;
        this.BKCJ = BKCJ;
        this.JD = JD;
        this.CXBJ = CXBJ;
        this.KCXZ = KCXZ;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getXN() {
        return XN;
    }

    public void setXN(String XN) {
        this.XN = XN;
    }

    public String getXQ() {
        return XQ;
    }

    public void setXQ(String XQ) {
        this.XQ = XQ;
    }

    public String getXKKH() {
        return XKKH;
    }

    public void setXKKH(String XKKH) {
        this.XKKH = XKKH;
    }

    public String getKCMC() {
        return KCMC;
    }

    public void setKCMC(String KCMC) {
        this.KCMC = KCMC;
    }

    public String getXF() {
        return XF;
    }

    public void setXF(String XF) {
        this.XF = XF;
    }

    public String getCJ() {
        return CJ;
    }

    public void setCJ(String CJ) {
        this.CJ = CJ;
    }

    public String getZSCJ() {
        return ZSCJ;
    }

    public void setZSCJ(String ZSCJ) {
        this.ZSCJ = ZSCJ;
    }

    public String getBKCJ() {
        return BKCJ;
    }

    public void setBKCJ(String BKCJ) {
        this.BKCJ = BKCJ;
    }

    public String getJD() {
        return JD;
    }

    public void setJD(String JD) {
        this.JD = JD;
    }

    public String getCXBJ() {
        return CXBJ;
    }

    public void setCXBJ(String CXBJ) {
        this.CXBJ = CXBJ;
    }

    public String getKCXZ() {
        return KCXZ;
    }

    public void setKCXZ(String KCXZ) {
        this.KCXZ = KCXZ;
    }

}
