package com.gaop.huthelperdao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import com.gaop.huthelper.app.MApplication;
import com.gaop.huthelper.utils.PrefUtil;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 13): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 13;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserDao.createTable(db, ifNotExists);
        LessonDao.createTable(db, ifNotExists);
        TremDao.createTable(db, ifNotExists);
        CourseGradeDao.createTable(db, ifNotExists);
        GradeDao.createTable(db, ifNotExists);
        NoticeDao.createTable(db, ifNotExists);
        ExplessonDao.createTable(db, ifNotExists);
        ExamDao.createTable(db, ifNotExists);
        MenuDao.createTable(db, ifNotExists);
        RankingDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserDao.dropTable(db, ifExists);
        LessonDao.dropTable(db, ifExists);
        TremDao.dropTable(db, ifExists);
        CourseGradeDao.dropTable(db, ifExists);
        GradeDao.dropTable(db, ifExists);
        NoticeDao.dropTable(db, ifExists);
        ExplessonDao.dropTable(db, ifExists);
        ExamDao.dropTable(db, ifExists);
        MenuDao.dropTable(db, ifExists);
        RankingDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
            PrefUtil.setBoolean(MApplication.AppContext, "isLoadExam", false);
            PrefUtil.setBoolean(MApplication.AppContext, "isLoadUser", false);
            PrefUtil.setBoolean(MApplication.AppContext, "isLoadCourseTable", false);
            PrefUtil.setBoolean(MApplication.AppContext, "isLoadGrade", false);
            PrefUtil.setBoolean(MApplication.AppContext, "isLoadExpLesson", false);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserDao.class);
        registerDaoClass(LessonDao.class);
        registerDaoClass(TremDao.class);
        registerDaoClass(CourseGradeDao.class);
        registerDaoClass(GradeDao.class);
        registerDaoClass(NoticeDao.class);
        registerDaoClass(ExplessonDao.class);
        registerDaoClass(ExamDao.class);
        registerDaoClass(MenuDao.class);
        registerDaoClass(RankingDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
