package com.gaop.huthelperdao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gaop.huthelperdao.User;
import com.gaop.huthelperdao.Lesson;
import com.gaop.huthelperdao.Trem;
import com.gaop.huthelperdao.CourseGrade;
import com.gaop.huthelperdao.Grade;
import com.gaop.huthelperdao.Notice;
import com.gaop.huthelperdao.Explesson;
import com.gaop.huthelperdao.Exam;
import com.gaop.huthelperdao.Menu;
import com.gaop.huthelperdao.Ranking;

import com.gaop.huthelperdao.UserDao;
import com.gaop.huthelperdao.LessonDao;
import com.gaop.huthelperdao.TremDao;
import com.gaop.huthelperdao.CourseGradeDao;
import com.gaop.huthelperdao.GradeDao;
import com.gaop.huthelperdao.NoticeDao;
import com.gaop.huthelperdao.ExplessonDao;
import com.gaop.huthelperdao.ExamDao;
import com.gaop.huthelperdao.MenuDao;
import com.gaop.huthelperdao.RankingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig lessonDaoConfig;
    private final DaoConfig tremDaoConfig;
    private final DaoConfig courseGradeDaoConfig;
    private final DaoConfig gradeDaoConfig;
    private final DaoConfig noticeDaoConfig;
    private final DaoConfig explessonDaoConfig;
    private final DaoConfig examDaoConfig;
    private final DaoConfig menuDaoConfig;
    private final DaoConfig rankingDaoConfig;

    private final UserDao userDao;
    private final LessonDao lessonDao;
    private final TremDao tremDao;
    private final CourseGradeDao courseGradeDao;
    private final GradeDao gradeDao;
    private final NoticeDao noticeDao;
    private final ExplessonDao explessonDao;
    private final ExamDao examDao;
    private final MenuDao menuDao;
    private final RankingDao rankingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
        lessonDaoConfig.initIdentityScope(type);

        tremDaoConfig = daoConfigMap.get(TremDao.class).clone();
        tremDaoConfig.initIdentityScope(type);

        courseGradeDaoConfig = daoConfigMap.get(CourseGradeDao.class).clone();
        courseGradeDaoConfig.initIdentityScope(type);

        gradeDaoConfig = daoConfigMap.get(GradeDao.class).clone();
        gradeDaoConfig.initIdentityScope(type);

        noticeDaoConfig = daoConfigMap.get(NoticeDao.class).clone();
        noticeDaoConfig.initIdentityScope(type);

        explessonDaoConfig = daoConfigMap.get(ExplessonDao.class).clone();
        explessonDaoConfig.initIdentityScope(type);

        examDaoConfig = daoConfigMap.get(ExamDao.class).clone();
        examDaoConfig.initIdentityScope(type);

        menuDaoConfig = daoConfigMap.get(MenuDao.class).clone();
        menuDaoConfig.initIdentityScope(type);

        rankingDaoConfig = daoConfigMap.get(RankingDao.class).clone();
        rankingDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        lessonDao = new LessonDao(lessonDaoConfig, this);
        tremDao = new TremDao(tremDaoConfig, this);
        courseGradeDao = new CourseGradeDao(courseGradeDaoConfig, this);
        gradeDao = new GradeDao(gradeDaoConfig, this);
        noticeDao = new NoticeDao(noticeDaoConfig, this);
        explessonDao = new ExplessonDao(explessonDaoConfig, this);
        examDao = new ExamDao(examDaoConfig, this);
        menuDao = new MenuDao(menuDaoConfig, this);
        rankingDao = new RankingDao(rankingDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Lesson.class, lessonDao);
        registerDao(Trem.class, tremDao);
        registerDao(CourseGrade.class, courseGradeDao);
        registerDao(Grade.class, gradeDao);
        registerDao(Notice.class, noticeDao);
        registerDao(Explesson.class, explessonDao);
        registerDao(Exam.class, examDao);
        registerDao(Menu.class, menuDao);
        registerDao(Ranking.class, rankingDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        lessonDaoConfig.getIdentityScope().clear();
        tremDaoConfig.getIdentityScope().clear();
        courseGradeDaoConfig.getIdentityScope().clear();
        gradeDaoConfig.getIdentityScope().clear();
        noticeDaoConfig.getIdentityScope().clear();
        explessonDaoConfig.getIdentityScope().clear();
        examDaoConfig.getIdentityScope().clear();
        menuDaoConfig.getIdentityScope().clear();
        rankingDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LessonDao getLessonDao() {
        return lessonDao;
    }

    public TremDao getTremDao() {
        return tremDao;
    }

    public CourseGradeDao getCourseGradeDao() {
        return courseGradeDao;
    }

    public GradeDao getGradeDao() {
        return gradeDao;
    }

    public NoticeDao getNoticeDao() {
        return noticeDao;
    }

    public ExplessonDao getExplessonDao() {
        return explessonDao;
    }

    public ExamDao getExamDao() {
        return examDao;
    }

    public MenuDao getMenuDao() {
        return menuDao;
    }

    public RankingDao getRankingDao() {
        return rankingDao;
    }

}
