package com.gaop.huthelperdao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gaop.huthelperdao.User;
import com.gaop.huthelperdao.Lesson;
import com.gaop.huthelperdao.Trem;
import com.gaop.huthelperdao.CourseGrade;
import com.gaop.huthelperdao.Grade;

import com.gaop.huthelperdao.UserDao;
import com.gaop.huthelperdao.LessonDao;
import com.gaop.huthelperdao.TremDao;
import com.gaop.huthelperdao.CourseGradeDao;
import com.gaop.huthelperdao.GradeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig lessonDaoConfig;
    private final DaoConfig tremDaoConfig;
    private final DaoConfig courseGradeDaoConfig;
    private final DaoConfig gradeDaoConfig;

    private final UserDao userDao;
    private final LessonDao lessonDao;
    private final TremDao tremDao;
    private final CourseGradeDao courseGradeDao;
    private final GradeDao gradeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
        lessonDaoConfig.initIdentityScope(type);

        tremDaoConfig = daoConfigMap.get(TremDao.class).clone();
        tremDaoConfig.initIdentityScope(type);

        courseGradeDaoConfig = daoConfigMap.get(CourseGradeDao.class).clone();
        courseGradeDaoConfig.initIdentityScope(type);

        gradeDaoConfig = daoConfigMap.get(GradeDao.class).clone();
        gradeDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        lessonDao = new LessonDao(lessonDaoConfig, this);
        tremDao = new TremDao(tremDaoConfig, this);
        courseGradeDao = new CourseGradeDao(courseGradeDaoConfig, this);
        gradeDao = new GradeDao(gradeDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Lesson.class, lessonDao);
        registerDao(Trem.class, tremDao);
        registerDao(CourseGrade.class, courseGradeDao);
        registerDao(Grade.class, gradeDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        lessonDaoConfig.getIdentityScope().clear();
        tremDaoConfig.getIdentityScope().clear();
        courseGradeDaoConfig.getIdentityScope().clear();
        gradeDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LessonDao getLessonDao() {
        return lessonDao;
    }

    public TremDao getTremDao() {
        return tremDao;
    }

    public CourseGradeDao getCourseGradeDao() {
        return courseGradeDao;
    }

    public GradeDao getGradeDao() {
        return gradeDao;
    }

}
