package com.gaop.huthelperdao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EXAM".
 */
public class Exam {

    private Long id;
    private String CourseName;
    private String Starttime;
    private String EndTime;
    private String Week_Num;
    private String isset;
    private String RoomName;
    private Boolean isCx;

    public Exam() {
    }

    public Exam(Long id) {
        this.id = id;
    }

    public Exam(Long id, String CourseName, String Starttime, String EndTime, String Week_Num, String isset, String RoomName, Boolean isCx) {
        this.id = id;
        this.CourseName = CourseName;
        this.Starttime = Starttime;
        this.EndTime = EndTime;
        this.Week_Num = Week_Num;
        this.isset = isset;
        this.RoomName = RoomName;
        this.isCx = isCx;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCourseName() {
        return CourseName;
    }

    public void setCourseName(String CourseName) {
        this.CourseName = CourseName;
    }

    public String getStarttime() {
        return Starttime;
    }

    public void setStarttime(String Starttime) {
        this.Starttime = Starttime;
    }

    public String getEndTime() {
        return EndTime;
    }

    public void setEndTime(String EndTime) {
        this.EndTime = EndTime;
    }

    public String getWeek_Num() {
        return Week_Num;
    }

    public void setWeek_Num(String Week_Num) {
        this.Week_Num = Week_Num;
    }

    public String getIsset() {
        return isset;
    }

    public void setIsset(String isset) {
        this.isset = isset;
    }

    public String getRoomName() {
        return RoomName;
    }

    public void setRoomName(String RoomName) {
        this.RoomName = RoomName;
    }

    public Boolean getIsCx() {
        return isCx;
    }

    public void setIsCx(Boolean isCx) {
        this.isCx = isCx;
    }

}
