package com.gaop.huthelperdao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GRADE".
 */
public class Grade {

    private Long id;
    private Float allsf;
    private Float getsf;
    private Float cxsf;
    private Float nopassxf;
    private Float avgScore;
    private Float avgJd;
    private Integer noPassNum;
    private Integer allNum;

    public Grade() {
    }

    public Grade(Long id) {
        this.id = id;
    }

    public Grade(Long id, Float allsf, Float getsf, Float cxsf, Float nopassxf, Float avgScore, Float avgJd, Integer noPassNum, Integer allNum) {
        this.id = id;
        this.allsf = allsf;
        this.getsf = getsf;
        this.cxsf = cxsf;
        this.nopassxf = nopassxf;
        this.avgScore = avgScore;
        this.avgJd = avgJd;
        this.noPassNum = noPassNum;
        this.allNum = allNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getAllsf() {
        return allsf;
    }

    public void setAllsf(Float allsf) {
        this.allsf = allsf;
    }

    public Float getGetsf() {
        return getsf;
    }

    public void setGetsf(Float getsf) {
        this.getsf = getsf;
    }

    public Float getCxsf() {
        return cxsf;
    }

    public void setCxsf(Float cxsf) {
        this.cxsf = cxsf;
    }

    public Float getNopassxf() {
        return nopassxf;
    }

    public void setNopassxf(Float nopassxf) {
        this.nopassxf = nopassxf;
    }

    public Float getAvgScore() {
        return avgScore;
    }

    public void setAvgScore(Float avgScore) {
        this.avgScore = avgScore;
    }

    public Float getAvgJd() {
        return avgJd;
    }

    public void setAvgJd(Float avgJd) {
        this.avgJd = avgJd;
    }

    public Integer getNoPassNum() {
        return noPassNum;
    }

    public void setNoPassNum(Integer noPassNum) {
        this.noPassNum = noPassNum;
    }

    public Integer getAllNum() {
        return allNum;
    }

    public void setAllNum(Integer allNum) {
        this.allNum = allNum;
    }

}
