package com.gaop.huthelperdao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "MENU".
 */
public class Menu implements java.io.Serializable{

    private Long id;
    private Integer index;
    private String path;
    private String title;
    private Integer msg;
    private Integer picId;
    private Boolean isMain;

    public Menu() {
    }

    public Menu(String path, String title, int picId, int index, boolean isMain, int msg) {
        this.path = path;
        this.title = title;
        this.msg = msg;
        this.isMain = isMain;
        this.picId = picId;
        this.index = index;
    }

    public Menu(Long id) {
        this.id = id;
    }

    public Menu(Long id, Integer index, String path, String title, Integer msg, Integer picId, Boolean isMain) {
        this.id = id;
        this.index = index;
        this.path = path;
        this.title = title;
        this.msg = msg;
        this.picId = picId;
        this.isMain = isMain;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getMsg() {
        return msg;
    }

    public void setMsg(Integer msg) {
        this.msg = msg;
    }

    public Integer getPicId() {
        return picId;
    }

    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    public Boolean getIsMain() {
        return isMain;
    }

    public void setIsMain(Boolean isMain) {
        this.isMain = isMain;
    }

}
