package com.gaop.huthelperdao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTICE".
 */
public class Notice implements java.io.Serializable {

    private Long id;
    private String time;
    private String content;
    private String title;

    public Notice() {
    }

    public Notice(Long id) {
        this.id = id;
    }

    public Notice(Long id, String time, String content, String title) {
        this.id = id;
        this.time = time;
        this.content = content;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
