package com.gaop.huthelperdao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RANKING".
 */
public class Ranking {

    private Long id;
    private String XN;
    private String XQ;
    private String ZJD;
    private Integer MC;
    private Boolean ISXN;
    private Boolean ISBJ;

    public Ranking() {
    }

    public Ranking(Long id) {
        this.id = id;
    }

    public Ranking(Long id, String XN, String XQ, String ZJD, Integer MC, Boolean ISXN, Boolean ISBJ) {
        this.id = id;
        this.XN = XN;
        this.XQ = XQ;
        this.ZJD = ZJD;
        this.MC = MC;
        this.ISXN = ISXN;
        this.ISBJ = ISBJ;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getXN() {
        return XN;
    }

    public void setXN(String XN) {
        this.XN = XN;
    }

    public String getXQ() {
        return XQ;
    }

    public void setXQ(String XQ) {
        this.XQ = XQ;
    }

    public String getZJD() {
        return ZJD;
    }

    public void setZJD(String ZJD) {
        this.ZJD = ZJD;
    }

    public Integer getMC() {
        return MC;
    }

    public void setMC(Integer MC) {
        this.MC = MC;
    }

    public Boolean getISXN() {
        return ISXN;
    }

    public void setISXN(Boolean ISXN) {
        this.ISXN = ISXN;
    }

    public Boolean getISBJ() {
        return ISBJ;
    }

    public void setISBJ(Boolean ISBJ) {
        this.ISBJ = ISBJ;
    }

}
