package com.gaop.huthelperdao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TREM".
 */
public class Trem {

    private Long id;
    private String XN;
    private String XQ;
    private String content;

    public Trem() {
    }

    public Trem(Long id) {
        this.id = id;
    }

    public Trem(Long id, String XN, String XQ, String content) {
        this.id = id;
        this.XN = XN;
        this.XQ = XQ;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getXN() {
        return XN;
    }

    public void setXN(String XN) {
        this.XN = XN;
    }

    public String getXQ() {
        return XQ;
    }

    public void setXQ(String XQ) {
        this.XQ = XQ;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
    @Override
    public boolean equals(Object o) {
        if(o instanceof Trem){
            if(((Trem) o).getXN().equals(this.XN)&&((Trem) o).getXQ().equals(this.XQ)){
                return true;
            }
        }
        return super.equals(o);
    }

    @Override
    public int hashCode() {
        return (XN!=null?XN.hashCode():1)*31+XQ.hashCode();
    }


}
